services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_container
    ports:
      - "8080:80"
      - "9003:9003"  # <-- Puerto Xdebug
    volumes:
      - ./src:/var/www/html
      - ./php-config:/usr/local/etc/php
      # - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb:10.6
    container_name: mariadb_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mysql-data:


networks:
  app-network:
    driver: bridge
